version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_gtclone
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: sample
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=pass"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_gtclone
    environment:
      - PMA_HOST=mysql 
      - PMA_USER=admin
      - PMA_PASSWORD=admin
    ports:
      - "8089:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge